export const ingatlanokData = [
    {
        id: 1,
        name: "Luxus lakás Budapesten",
        description: "Egy csodálatos, tágas lakás a belváros szívében.",
        price: 45000000,
        image: "/images/hero1.jpg",
        postedBy: "Kovács József",
        location: "Budapest",
    },
    {
        id: 2,
        name: "Családi ház Debrecenben",
        description: "Négy hálószobás családi ház csendes kertvárosi környezetben.",
        price: 25000000,
        image: "/images/hero2.jpg",
        postedBy: "Szabó Anna",
        location: "Debrecen",
    },
    {
        id: 3,
        name: "Telek eladó a Balaton partján",
        description: "Ideális helyszín nyaraló építésére.",
        price: 12000000,
        image: "/images/hero3.jpg",
        postedBy: "Nagy Péter",
        location: "Szeged",
    },
    {
        id: 4,
        name: "Modern lakás Szegeden",
        description: "Kétszobás, erkélyes lakás központi elhelyezkedéssel.",
        price: 32000000,
        image: "/images/hero4.jpg",
        postedBy: "Tóth László",
        location: "Sátoraljaújhely",
    },
    {
        id: 5,
        name: "Kertes ház Pécsett",
        description: "Három hálószobás családi ház hatalmas kerttel és garázzsal.",
        price: 35000000,
        image: "/images/hero5.jpg",
        postedBy: "Varga Márton",
        location: "Pécs",
    },
    {
        id: 6,
        name: "Vidéki tanyasi ház",
        description: "Romantikus, vidéki környezetben eladó egy tanya.",
        price: 15000000,
        image: "/images/hero1.jpg",
        postedBy: "Farkas Béla",
        location: "Vidéki Terület",
    }
];